### ISSUE TITLE
Failure in portray command for docs

### ISSUE THREAD

**Issue by maresb** [cruft/cruft#156]
https://github.com/cruft/cruft/runs/6100661586?check_suite_focus=true

```
Run poetry run portray on_github_pages -f

⠋ Copying source documentation to temporary compilation directory
Done Copying source documentation to temporary compilation directory

⠋ Auto generating reference documentation using pdocs
⠙ Auto generating reference documentation using pdocs
⠹ Auto generating reference documentation using pdocs
Done Auto generating reference documentation using pdocs

⠋ Rendering complete website from Markdown using MkDocs
Traceback (most recent call last):
  File "/home/runner/work/cruft/cruft/.venv/bin/portray", line 8, in <module>
    sys.exit(__hug__.cli())
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/hug/api.py", line 441, in __call__
    result = self.commands.get(command)()
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/hug/interface.py", line 650, in __call__
    raise exception
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/hug/interface.py", line 646, in __call__
    result = self.output(self.interface(**pass_to_function), context)
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/portray/api.py", line 184, in on_github_pages
    with render.documentation_in_temp_folder(project_config) as (_, site_dir):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/portray/render.py", line 155, in documentation_in_temp_folder
    mkdocs(config["mkdocs"])
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/portray/render.py", line 69, in mkdocs
    config_instance = _mkdocs_config(config)
  File "/home/runner/work/cruft/cruft/.venv/lib/python3.7/site-packages/portray/render.py", line 172, in _mkdocs_config
    config_instance = mkdocs_config.Config(schema=mkdocs_config.DEFAULT_SCHEMA)
AttributeError: module 'mkdocs.config' has no attribute 'DEFAULT_SCHEMA'
```

**Comment by samj1912** [comment]
https://github.com/timothycrosley/portray/issues/83 related issue. Just a version bump to 1.7 should work.
