### ISSUE TITLE
Cruft not running with macOS Ventura + python 3.11 

### ISSUE THREAD

**Issue by AbdelrhmanHamouda** [cruft/cruft#260]
Issue: 
Attempting to run Cruft on my macOS with python 3.11.4 returns an error.  Switching to a python 3.10.x 

Details: 
Apple M1 Pro
OS version: Ventura Version 13.4 (22F66)
Python version: Python 3.11.4
cruft version: 2.15.0
Installation method:  `brew install cruft` 

Error: 
```bash
❯ cruft
Traceback (most recent call last):
  File "/opt/homebrew/bin/cruft", line 5, in <module>
    from cruft._cli import app
  File "/opt/homebrew/Cellar/cruft/2.15.0/libexec/lib/python3.11/site-packages/cruft/__init__.py", line 6, in <module>
    from cruft._commands import check, create, diff, link, update
  File "/opt/homebrew/Cellar/cruft/2.15.0/libexec/lib/python3.11/site-packages/cruft/_commands/__init__.py", line 2, in <module>
    from .check import check
  File "/opt/homebrew/Cellar/cruft/2.15.0/libexec/lib/python3.11/site-packages/cruft/_commands/check.py", line 5, in <module>
    import typer
  File "/opt/homebrew/Cellar/cruft/2.15.0/libexec/lib/python3.11/site-packages/typer/__init__.py", line 7, in <module>
    from click.exceptions import Abort as Abort
ModuleNotFoundError: No module named 'click'
```

**Comment by samj1912** [comment]
@AbdelrhmanHamouda we do not own the brew package and it is maintained by someone else. Your best bet is to reach out to the brew package maintainers for cruft. Closing this for now.
