### ISSUE TITLE
`cruft update` leads to `UnicodeDecodeError`

### ISSUE THREAD

**Issue by tdhopper** [cruft/cruft#81]
I've been trying Cruft for the first time, and I have hit this `UnicodeDecode` error doing a `cruft update` several times. 

I would be happy to try to debug this if you can give me an guidance on how I might go about that.

```
INFO    - fetching tags from remote (to turn off use: -n / --no-fetch)
INFO    - Old Version: 1970.1.1
INFO    - New Version: 2021.1.26
INFO    - git commit --message 'bump version 1970.1.1 -> 2021.1.26'
INFO    - git tag --annotate 2021.1.26 --message 2021.1.26
Traceback (most recent call last):
  File "/Users/user/.local/bin/cruft", line 8, in <module>
    sys.exit(app())
  File "/Users/user/.local/pipx/venvs/cruft/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/user/.local/pipx/venvs/cruft/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/.local/pipx/venvs/cruft/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/user/.local/pipx/venvs/cruft/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/.local/pipx/venvs/cruft/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/.local/pipx/venvs/cruft/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/user/.local/pipx/venvs/cruft/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/user/.local/pipx/venvs/cruft/lib/python3.7/site-packages/cruft/_cli.py", line 231, in update
    strict=strict,
  File "/Users/user/.local/pipx/venvs/cruft/lib/python3.7/site-packages/cruft/_commands/utils/__init__.py", line 14, in wrapper
    return f(*args, **kwargs)
  File "/Users/user/.local/pipx/venvs/cruft/lib/python3.7/site-packages/cruft/_commands/utils/__init__.py", line 14, in wrapper
    return f(*args, **kwargs)
  File "/Users/user/.local/pipx/venvs/cruft/lib/python3.7/site-packages/cruft/_commands/update.py", line 84, in update
    current_template_dir, new_template_dir, project_dir, skip_update, skip_apply_ask
  File "/Users/user/.local/pipx/venvs/cruft/lib/python3.7/site-packages/cruft/_commands/update.py", line 185, in _apply_project_updates
    diff = utils.diff.get_diff(old_main_directory, new_main_directory)
  File "/Users/user/.local/pipx/venvs/cruft/lib/python3.7/site-packages/cruft/_commands/utils/diff.py", line 16, in get_diff
    stderr=PIPE,
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 6024: invalid start byte
```

I'm on cruft 2.6.0.

**Comment by juhuebner** [comment]
The output of `git diff` possibly contains changes in some binary files. Possibly changing in `diff.py`
```
    diff = run(
        _git_diff("--no-ext-diff", "--no-color", repo0_str, repo1_str),
        cwd=repo0_str,
        stdout=PIPE,
        stderr=PIPE,
    ).stdout.decode()
```

to
```
    diff = run(
        _git_diff("--no-ext-diff", "--no-color", repo0_str, repo1_str),
        cwd=repo0_str,
        stdout=PIPE,
        stderr=PIPE,
    ).stdout.decode(encoding="utf-8", errors="ignore")
```

might help.

**Comment by juhuebner** [comment]
Possibly if you have a git repo installed with the template, there might be binaries as well due to packaging etc. In order to exclude this you want to add something like:
```toml
[tool.cruft]
skip = [".git"]
```

**Comment by tdhopper** [comment]
@juhuebner Skipping .git doesn't resolve the issue for me

**Comment by tdhopper** [comment]
It seems like the issue may be installing with [pipx](https://github.com/pipxproject/pipx) instead of installing into the project venv.

**Comment by juhuebner** [comment]
Possibly the `toml` package is included within the dependencies of `pipx` and had not been installed before. Currently the `toml` package is only included as a option in https://github.com/cruft/cruft/blob/74ccd3b1e012aebd5ed95f86169e45b625386d6f/pyproject.toml#L13 and thus not automatically installed via pip. This certainly has to be changed at some point...

**Comment by tdhopper** [comment]
Sorry for all the confusion, I think toml probably is the issue. I realized when I tested it in the venv again, I wasn't ignoring .git files.
